server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:demo1}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:user1}
    password: ${MYSQL_PASSWORD:user1}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

feign:
  sentinel:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: inventory_tx_group
  service:
    vgroup-mapping:
      inventory_tx_group: default
    grouplist:
      default: ${SEATA_HOST:127.0.0.1}:8091
