transport {
  type = "TCP"
  server = "file"
  heartbeat = true
  serialization = "seata"
  compressor = "none"
  enableClientBatchSendRequest = true
}

service {
  vgroupMapping.inventory_tx_group = "default"
  default.grouplist = "127.0.0.1:8091"
  enableDegrade = false
  disableGlobalTransaction = false
}

client {
  rm {
    asyncCommitBufferLimit = 10000
    lock {
      retryInterval = 10
      retryTimes = 30
      isLockRetryPolicyBranchRollbackOnConflict = true
    }
  }
  tm {
    commitRetryCount = 5
    rollbackRetryCount = 5
  }
}
